### ISSUE TITLE
Crystal 0.35.0

### ISSUE THREAD

**Issue by russ** [KCErb/lucky-hasura-docker#1]
I'm working on getting my app upgraded to Crystal 0.35.0. I'm running into all sorts of issues with shards being updated and not working on 0.34.0. I see the latest tag on docker hub is lucky-crystal:l0.21.0c0.34.0-alpine.

Is there a way to build these or are you doing it manually?

**Comment by KCErb** [comment]
I have a tiny local repo that builds them. I can push up a new image now that Lucky is 0.35 compatible, but I'm also interested in looking at more automatic alternatives. Any suggestions?

**Comment by russ** [comment]
Maybe something can be setup with Github Actions? I haven't setup something like that up before but maybe this can help. https://github.com/marketplace/actions/build-and-push-docker-images

If  you push it up I could take a look at what all the options are.

**Comment by KCErb** [comment]
Cool, sounds interesting! I'll take a look at this and the PR tonight after work. In the meantime, I'm pushing up a new docker image so that this doesn't slow anyone down.

**Comment by KCErb** [comment]
There's a new Crystal 0.35 compatible image up on dockerhub now: https://hub.docker.com/repository/docker/luckyhasuradocker/lucky-crystal/general

I'll close this and open a new one about looking into using Github Actions or something similar to automate this.
